# Generated by Django 4.2.4 on 2023-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.TextField(db_column="cust_name", max_length=50),
                ),
                ("customer_dob", models.DateField(db_column="cust_dob")),
                (
                    "customer_address",
                    models.TextField(db_column="cust_address", max_length=200),
                ),
                (
                    "customer_country",
                    models.TextField(db_column="cust_country", max_length=20),
                ),
                (
                    "customer_mobile",
                    models.TextField(db_column="cust_mobile", max_length=10),
                ),
                (
                    "customer_email",
                    models.TextField(db_column="cust_email", max_length=50),
                ),
                (
                    "customer_password",
                    models.TextField(db_column="cust_password", max_length=20),
                ),
                (
                    "customer_gender",
                    models.TextField(db_column="cust_gender", max_length=10),
                ),
                ("otp", models.TextField(db_column="otp", max_length=10, null=True)),
                (
                    "status",
                    models.TextField(
                        db_column="status", default="", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
    ]
