# Generated by Django 4.2.4 on 2023-09-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0002_remove_sellers_resel_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(db_column="product_title", max_length=30)),
                (
                    "reg_productid",
                    models.TextField(db_column="product_id", max_length=12),
                ),
                ("desc", models.TextField(db_column="desc", max_length=200)),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        db_column="image",
                        null=True,
                        upload_to="product_images/",
                    ),
                ),
                ("price", models.IntegerField(db_column="price")),
                ("quantity", models.IntegerField(db_column="quantity")),
                ("weight", models.IntegerField(db_column="weight")),
                ("weightunit", models.CharField(db_column="wieghtunit", max_length=12)),
                (
                    "brand",
                    models.CharField(db_column="brand", default="", max_length=20),
                ),
                ("status", models.CharField(db_column="status", max_length=100)),
                (
                    "resel_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seller.sellers",
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
    ]
